### ISSUE TITLE
Build shared library for Android 

### ISSUE THREAD

**Issue by dpproduction** [libgdx/fbx-conv#104]
I'd like to compile this library for Android devices with arm processors. Converter depends on fbxsdk.so but this sdk builded for linux not for android arm. Is it possible to use this prebuild fbxsdk.so for arembi-v7 ?

**Comment by GameCy** [comment]
Why do you need to run a command line utility from android? It's supposed to run at build time to convert  to friendlier formats. Then you include the converted files in your android app.

**Comment by dpproduction** [comment]
Because I wanted to write 3d viewer based on libGDX that can read .fbx and .dae formats.

**Comment by GameCy** [comment]
You would need a library that was built for Arm processors. Adobe doesn't seem to have support for Android. 
If you need it really bad you could try to port the below project to libGDx and see how far you will get: 

https://github.com/hamish-milne/FbxWriter/tree/master/Fbx

or 

https://github.com/yamahigashi/FBXLoaderJS/blob/master/js/loaders/three.FBXLoader.js
