### ISSUE TITLE
parsing the ts.fbx file Mesh Data position error....

### ISSUE THREAD

**Issue by qwe5788319** [libgdx/fbx-conv#105]

**Comment by qwe5788319** [comment]
[Uploading ts.zip…](ts.fbx)

**Comment by qwe5788319** [comment]
[ts.zip](https://github.com/libgdx/fbx-conv/files/1230624/ts.zip)
give to you testing

**Comment by xoppa** [comment]
https://github.com/libgdx/libgdx/wiki/Issue-Tracker
