### ISSUE TITLE
libfbxsdk.so and libfbxsdk.dylib ?

### ISSUE THREAD

**Issue by hopewise** [libgdx/fbx-conv#109]
Where can I find libfbxsdk.so and libfbxsdk.dylib files?

**Comment by Tom-Ski** [comment]
FBX sdk

**Comment by happypandaface** [comment]
had a lot of trouble finding this. you have to goto the archives:
https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-archives
https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2014-2-1

here are instructions:
https://help.autodesk.com/view/FBX/2016/ENU/?guid=__files_GUID_408B9928_104E_463E_994D_ACD4CB8341A9_htm

I got it working just updating the LD_LIBRARY_PATH on ubuntu 18
