### ISSUE TITLE
Android based development

### ISSUE THREAD

**Issue by anonimo82** [libgdx/fbx-conv#125]
Hello everyone.
I'd like to use LibGDX with AIDE on Android (http://android-ide.com/), so I'd need to convert meshes on it.
Please, will anyone mind to port this converter to Android app?
Note there are good 3D modeling Apps on Android, together with AIDE and LibGDX, it's possible to code from Android, for Android.

Some 3D Apps for Android:
https://play.google.com/store/apps/details?id=com.inforcegames.app3dmodelling
https://play.google.com/store/apps/details?id=com.prisma3D.prisma3D

Thanks in advance for any.

**Comment by mgsx-dev** [comment]
alternatively, you can use GLTF format instead, [gdx-gltf](https://github.com/mgsx-dev/gdx-gltf) library allow you to import model directly without any conversion (Export feature will be implemented soon). There is an  [Android demo here](https://play.google.com/store/apps/details?id=net.mgsx.gltf.demo)

**Comment by anonimo82** [comment]
Wow, fantastic!
Thanks a lot, I'll do my best to use this as solution.
