### ISSUE TITLE
FBX-Conv generates incorrect animations from FBX exported from 3D Studio Max

### ISSUE THREAD

**Issue by Zoonmaan** [libgdx/fbx-conv#39]
First off, I use the tool "FBX Multi Take" from here:
http://www.turbosquid.com/FullPreview/Index.cfm/ID/701878   (there is a trial somewhere), and the trial version of 3D Studio Max 2010.

The Multi Take tool/plugin allows one to specify more than one animation in the exported FBX file. Out of the box, 3DS Max only supports one!

After exporting the FBX file, I open the file in "Autodesk FBX Converter 2013" (free). Here I can preview the takes, and verify that they work as expected.

After running them through the FBX-conv tool, it finds all the animations, eg. "Walk", "Run", "Attack" and so forth. But when I try to play the animation in LibGDX, it always plays the entire animation (Walk+Run+Attack). Looking at the generated g3dj file, all the animations "keyframes":"keytime" start at 0.000000

**Comment by goph-R** [comment]
Hi!

I had a similar problem (opacity problem with the current downloadable binary: http://libgdx.badlogicgames.com/fbx-conv, bone transform problem with this version: http://blog.xoppa.com/wp-content/uploads/2015/02/fbx-conv-win.zip), but the linked version above worked perfectly.
