### ISSUE TITLE
Support for morph targets / blend shapes in FBX format

### ISSUE THREAD

**Issue by garciahurtado** [libgdx/fbx-conv#73]
There are some kinds of animations that cannot be easily replicated with skeletal animations. One such example would be an exploding object, where multiple faces are moving in different directions at once. Some facial expressions are also much easier to create using morph targets.

Since FBX does support morph targets / blend shapes / shape keys, It would be great if support could be added to the fbx-conv tool, with the ultimate goal of also adding support in libgdx core.

**Comment by xoppa** [comment]
Closing this, continue on https://github.com/libgdx/libgdx/issues/2633
