### ISSUE TITLE
FBX 7.4 incorrect orientation

### ISSUE THREAD

**Issue by htaudah** [libgdx/fbx-conv#77]
When exporting my .fbx from Blender, if I choose Version 7.4 the resulting model would always be oriented face down to the ground. The axis settings in Blender have no effect. (The scaling also seems to be a little different from Blender settings, but I'm not sure).

I guess I could rotate the model and scale in-game, but it would be great if this were corrected.
http://www.filedropper.com/woodtower

**Comment by xoppa** [comment]
Can't reproduce, works fine for me. Make sure to use latest versions. Also provide enough information to reproduce the issue you're reporting.

**Comment by htaudah** [comment]
I'm on 1.5.4 and the latest version of fbx-conv-win32.
Perhaps I should have been clearer on the desired orientation, the model I posted above is going to be seen from above (its a top-view game). fbx-conv seems to be disregarding whatever orientation settings I use when exporting from Blender.
![blenderexport](https://cloud.githubusercontent.com/assets/7574973/6400426/e145afbc-be09-11e4-91fd-29e3138544a6.jpg)

This issue is also discussed here: http://www.badlogicgames.com/forum/viewtopic.php?f=11&t=15060
Apparently the problem started with Blender 2.71 (I'm on 2.73).

This is all I'm doing:
1) Export from Blender with the settings above.
2) fbx-conv-win32 with -f flag only.
3) Model doesn't appear top-down in game.

Here is my blender file: http://www.filedropper.com/woodtower_1

**Comment by xoppa** [comment]
That's by design and documented: https://github.com/libgdx/libgdx/wiki/Importing-Blender-models-in-LibGDX#setting-the-coordinate-system-up-axis
