### ISSUE TITLE
Issues executing from apache2/php

### ISSUE THREAD

**Issue by evilcats** [libgdx/fbx-conv#79]
Hey guys! little confused here. 
working on a project where I execute from apache/php

exec("/opt/fbxconv/fbx-conv-lin64 -o G3DB '/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx' '/var/www/#censor#/public_html/#censor#/assets/FBXUploads/FBXUpload_546/mytest.g3db'");

I've tried executing the same command from the terminal with these results:

INFO:     FBX to G3Dx converter, version 0.01.0037 x64 (pre-release)
STATUS:   Loading source file
WARNING:  [Cube] Node uses RrSs mode, transformation might be incorrect
STATUS:   [Cube] Triangulating FbxMesh geometry
Segmentation fault

Below is an strace of the application! any help is much appreciated!

execve("/opt/fbxconv/fbx-conv-lin64", ["/opt/fbxconv/fbx-conv-lin64", "/var/www/#censor#/public_ht"..., "/var/www/#censor#/public_ht"...], [/* 15 vars */]) = 0
brk(0)                                  = 0x1dc6000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e47000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=19589, ...}) = 0
mmap(NULL, 19589, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f30d5e42000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/libfbxsdk.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20l\24\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0444, st_size=9973618, ...}) = 0
mmap(NULL, 10319400, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d5251000
mprotect(0x7f30d5a01000, 2097152, PROT_NONE) = 0
mmap(0x7f30d5c01000, 147456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x7b0000) = 0x7f30d5c01000
mmap(0x7f30d5c25000, 13864, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f30d5c25000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14664, ...}) = 0
mmap(NULL, 2109712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d504d000
mprotect(0x7f30d5050000, 2093056, PROT_NONE) = 0
mmap(0x7f30d524f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f30d524f000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0@\6\6\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=991600, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e41000
mmap(NULL, 3171520, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d4d46000
mprotect(0x7f30d4e2e000, 2097152, PROT_NONE) = 0
mmap(0x7f30d502e000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe8000) = 0x7f30d502e000
mmap(0x7f30d5038000, 83136, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f30d5038000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p.\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=89056, ...}) = 0
mmap(NULL, 2184824, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d4b30000
mprotect(0x7f30d4b45000, 2097152, PROT_NONE) = 0
mmap(0x7f30d4d45000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15000) = 0x7f30d4d45000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\34\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1729984, ...}) = 0
mmap(NULL, 3836448, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d4787000
mprotect(0x7f30d4926000, 2097152, PROT_NONE) = 0
mmap(0x7f30d4b26000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19f000) = 0x7f30d4b26000
mmap(0x7f30d4b2c000, 14880, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f30d4b2c000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\200U\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1051056, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e40000
mmap(NULL, 3146072, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d4486000
mprotect(0x7f30d4586000, 2093056, PROT_NONE) = 0
mmap(0x7f30d4785000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xff000) = 0x7f30d4785000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20o\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=137440, ...}) = 0
mmap(NULL, 2213008, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f30d4269000
mprotect(0x7f30d4281000, 2093056, PROT_NONE) = 0
mmap(0x7f30d4480000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f30d4480000
mmap(0x7f30d4482000, 13456, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f30d4482000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e3f000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e3d000
arch_prctl(ARCH_SET_FS, 0x7f30d5e3d740) = 0
mprotect(0x7f30d4b26000, 16384, PROT_READ) = 0
mprotect(0x7f30d4480000, 4096, PROT_READ) = 0
mprotect(0x7f30d4785000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e3c000
mprotect(0x7f30d502e000, 32768, PROT_READ) = 0
mprotect(0x7f30d524f000, 4096, PROT_READ) = 0
mprotect(0x625000, 4096, PROT_READ)     = 0
mprotect(0x7f30d5e49000, 4096, PROT_READ) = 0
munmap(0x7f30d5e42000, 19589)           = 0
set_tid_address(0x7f30d5e3da10)         = 692
set_robust_list(0x7f30d5e3da20, 0x18)   = 0
rt_sigaction(SIGRTMIN, {0x7f30d426f9f0, [], SA_RESTORER|SA_SIGINFO, 0x7f30d42788d0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f30d426fa80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f30d42788d0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
futex(0x7f30d504a9e4, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f30d504a9f0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0)                                  = 0x1dc6000
brk(0x1de7000)                          = 0x1de7000
fstat(1, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 0), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e46000
write(1, "INFO:     FBX to G3Dx converter,"..., 69INFO:     FBX to G3Dx converter, version 0.01.0037 x64 (pre-release)
) = 69
write(1, "STATUS:   Loading source file\n", 30STATUS:   Loading source file
) = 30
brk(0x1e08000)                          = 0x1e08000
brk(0x1e29000)                          = 0x1e29000
brk(0x1e4a000)                          = 0x1e4a000
brk(0x1e6b000)                          = 0x1e6b000
getcwd("/opt/fbxconv", 1048)            = 13
openat(AT_FDCWD, "/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbd/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
stat("/var/www/#censor#/public_html#censor#/assets/Uploads/cube2.fbx", {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
open("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e45000
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 8192) = 8192
fstat(3, {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 2768) = 2768
lseek(3, 15056, SEEK_SET)               = 15056
read(3, "", 4096)                       = 0
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 2768) = 2768
lseek(3, 15056, SEEK_SET)               = 15056
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 457) = 457
close(3)                                = 0
munmap(0x7f30d5e45000, 4096)            = 0
getcwd("/opt/fbxconv", 1048)            = 13
openat(AT_FDCWD, "/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbd/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/var/www/#censor#public_html/#censor#/assets/Uploads/cube2.fbx", {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
stat("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
open("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e45000
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 8192) = 8192
fstat(3, {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 2768) = 2768
lseek(3, 15056, SEEK_SET)               = 15056
read(3, "", 4096)                       = 0
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 2768) = 2768
lseek(3, 15056, SEEK_SET)               = 15056
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 457) = 457
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 4096) = 4096
read(3, "DS\0\0\0\0D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360"..., 4096) = 4096
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 4096) = 4096
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 4096) = 2768
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 457) = 457
read(3, "\361\1\0\0\1\0\0\0\25\0\0\0\6FileIdR\20\0\0\0)\260)\352\267&\314\306"..., 8192) = 8192
lseek(3, 8192, SEEK_SET)                = 8192
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 3551) = 3551
read(3, "@.\0\0\0\0\0\0\0\0\0\0\vConnections3.\0\0\3\0\0\0"..., 8192) = 3313
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 740) = 740
read(3, "\375\2\0\0\1\0\0\0\5\0\0\0\7VersionId\0\0\0\24\3\0\0\1\0\0"..., 8192) = 8192
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 560) = 560
read(3, "X2\0\0\1\0\0\0\25\0\0\0\6FileIdR\20\0\0\0)\260)\352\267&\314\306"..., 8192) = 2208
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f30d5e45000, 4096)            = 0
getcwd("/opt/fbxconv", 1048)            = 13
openat(AT_FDCWD, "/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbd/", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
stat("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
open("/var/www/#censor#/public_html/#censor#/assets/Uploads/cube2.fbx", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5e45000
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 8192) = 8192
fstat(3, {st_mode=S_IFREG|0644, st_size=15056, ...}) = 0
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 2768) = 2768
lseek(3, 15056, SEEK_SET)               = 15056
read(3, "", 4096)                       = 0
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 2768) = 2768
lseek(3, 15056, SEEK_SET)               = 15056
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 457) = 457
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 4096) = 4096
read(3, "DS\0\0\0\0D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360"..., 4096) = 4096
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 4096) = 4096
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 4096) = 2768
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 457) = 457
read(3, "\361\1\0\0\1\0\0\0\25\0\0\0\6FileIdR\20\0\0\0)\260)\352\267&\314\306"..., 8192) = 8192
lseek(3, 8192, SEEK_SET)                = 8192
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 3551) = 3551
read(3, "@.\0\0\0\0\0\0\0\0\0\0\vConnections3.\0\0\3\0\0\0"..., 8192) = 3313
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 1041) = 1041
read(3, "\337#\0\0\2\0\0\0\31\0\0\0\5ModelS\v\0\0\0Cube\0\1Mod"..., 8192) = 8192
lseek(3, 8192, SEEK_SET)                = 8192
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 2443) = 2443
read(3, "\322-\0\0\0\0\0\0\0\0\0\0\16GlobalSettings\277)\0\0\1"..., 8192) = 4421
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 1041) = 1041
read(3, "\337#\0\0\2\0\0\0\31\0\0\0\5ModelS\v\0\0\0Cube\0\1Mod"..., 8192) = 8192
read(3, "\0\0\0UserData:$\0\0\1\0\0\0\r\0\0\0\4TypeS\10\0\0"..., 8192) = 5823
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 740) = 740
read(3, "\375\2\0\0\1\0\0\0\5\0\0\0\7VersionId\0\0\0\24\3\0\0\1\0\0"..., 8192) = 8192
lseek(3, 12288, SEEK_SET)               = 12288
read(3, "\0\0\0\3550\0\0\0\0\0\0\0\0\0\0\10Settings50\0\0\1\0\0\0"..., 560) = 560
read(3, "X2\0\0\1\0\0\0\25\0\0\0\6FileIdR\20\0\0\0)\260)\352\267&\314\306"..., 8192) = 2208
read(3, "", 4096)                       = 0
brk(0x1e8c000)                          = 0x1e8c000
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 645) = 645
read(3, "\233\2\0\0\1\0\0\0\5\0\0\0\4NameS\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 8192) = 8192
lseek(3, 8192, SEEK_SET)                = 8192
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 991) = 991
read(3, "\213)\0\0\2\0\0\0'\0\0\0\tSceneInfoS\25\0\0\0Globa"..., 8192) = 5873
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 1041) = 1041
read(3, "\337#\0\0\2\0\0\0\31\0\0\0\5ModelS\v\0\0\0Cube\0\1Mod"..., 8192) = 8192
read(3, "\0\0\0UserData:$\0\0\1\0\0\0\r\0\0\0\4TypeS\10\0\0"..., 8192) = 5823
read(3, "", 4096)                       = 0
lseek(3, 0, SEEK_SET)                   = 0
read(3, "Kaydara FBX Binary  \0\32\0\324\27\0\0\311\1\0\0\0"..., 1084) = 1084
read(3, "U\4\0\0\1\0\0\0\5\0\0\0\7VersionI\350\0\0\0\206\30\0\0\0\0\0"..., 8192) = 8192
read(3, "\0\0\1\0\0\0\5\0\0\0\7VersionId\0\0\0#%\0\0\0\0\0\0\0"..., 8192) = 5780
read(3, "", 4096)                       = 0
lseek(3, 8192, SEEK_SET)                = 8192
read(3, "\0\0\0\0\0\0\360?D\0\0\0\0\0\0\360?D\0\0\0\0\0\0\0\0D\0\0\0\0\0"..., 1052) = 1052
read(3, ":$\0\0\1\0\0\0\r\0\0\0\4TypeS\10\0\0\0UserDataS$"..., 8192) = 5812
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f30d5e45000, 4096)            = 0
write(1, "WARNING:  [Cube] Node uses RrSs "..., 72WARNING:  [Cube] Node uses RrSs mode, transformation might be incorrect
) = 72
write(1, "STATUS:   [Cube] Triangulating F"..., 48STATUS:   [Cube] Triangulating FbxMesh geometry
) = 48
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d5d3b000
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d4168000
mmap(NULL, 1052672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f30d4067000
munmap(0x7f30d5d3b000, 1052672)         = 0
munmap(0x7f30d4067000, 1052672)         = 0
munmap(0x7f30d4168000, 1052672)         = 0
brk(0x1fa9000)                          = 0x1fa9000
brk(0x20a9000)                          = 0x20a9000
brk(0x21a9000)                          = 0x21a9000
brk(0x1ea9000)                          = 0x1ea9000
brk(0x1fa9000)                          = 0x1fa9000
brk(0x20a9000)                          = 0x20a9000
brk(0x21a9000)                          = 0x21a9000
brk(0x1ea9000)                          = 0x1ea9000
brk(0x1fa9000)                          = 0x1fa9000
brk(0x20a9000)                          = 0x20a9000
brk(0x21a9000)                          = 0x21a9000
brk(0x1ea9000)                          = 0x1ea9000
brk(0x1fa9000)                          = 0x1fa9000
brk(0x20a9000)                          = 0x20a9000
brk(0x21a9000)                          = 0x21a9000
brk(0x1ea9000)                          = 0x1ea9000
brk(0x1fa9000)                          = 0x1fa9000
brk(0x20a9000)                          = 0x20a9000
brk(0x21a9000)                          = 0x21a9000
brk(0x1ea9000)                          = 0x1ea9000
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by xoppa** [comment]
Please provide the required assets to reproduce the issue you're reporting.

**Comment by evilcats** [comment]
you can download cube2.fbx from http://sol.henrybarker.co.nz/cube2.fbx
