### ISSUE TITLE
It does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by AntonKosov** [libgdx/fbx-conv#80]
fbx-conv-lin64 does not work on Ubuntu 14.04 (x64):

I have an error:

`fbx-conv-lin64: error while loading shared libraries: libfbxsdk.so: cannot open shared object file: No such file or directory`

**Comment by xoppa** [comment]
https://github.com/libgdx/fbx-conv#precompiled-binaries

**Comment by AntonKosov** [comment]
I tried to use version from here: http://libgdx.badlogicgames.com/fbx-conv
And this version doesn't work!

**Comment by utgarda** [comment]
@AntonKosov most likely that's beause with your system settings shared libraries ( .so ) aren't found in execution directory. Try putting `libfbxsdk.so` to /usr/lib64 or wherever your libraries reside, or instead use this command before running the binary:  `export LD_LIBRARY_PATH=.`
