### ISSUE TITLE
too many keyframes?

### ISSUE THREAD

**Issue by Kerai** [libgdx/fbx-conv#82]

**Comment by badlogic** [comment]
Does not compute.

**Comment by Kerai** [comment]
edited, github submitted they issue when i pressed enter on the title field. (not so conventional)

**Comment by badlogic** [comment]
We'll still need more info. How far apart are those keyframes in time? What interpolation is used? Etc.

**Comment by xoppa** [comment]
http://badlogicgames.com/forum/viewtopic.php?f=11&t=18494

**Comment by Kerai** [comment]
Yeah, I was going to write a longer post, get some models ready, but it got submitted before I could even write something. Sorry for inconvenience.
