### ISSUE TITLE
Building on OSX 10.10 (Yosemite) with FBX 2015

### ISSUE THREAD

**Issue by robindegen** [libgdx/fbx-conv#85]
In order to build on OSX Yosemite I had to modify the premake.lua file to fix some paths.

Attached here is a patch. I've not submitted this as a pull request as I have no idea how this will work out for the mentioned FBX sdk 2014 or older versions of OSX. This patch might break building with the 2014 sdk (which I could not find for download).

Ofcourse after this I also had to copy libfbxsdk.dylib from the fbx sdk to the local folder.

```
diff --git a/premake.lua b/premake.lua
index 5bac28c..acbbfa5 100644
--- a/premake.lua
+++ b/premake.lua
@@ -146,7 +146,7 @@ project "fbx-conv"
        kind "ConsoleApp"
        buildoptions { "-Wall" }
        libdirs {
-           (FBX_SDK_ROOT .. "/lib/gcc4/ub"),
+           (FBX_SDK_ROOT .. "/lib/clang"),
            "./libs/libpng/lib/macosx",
            "./libs/zlib/lib/macosx",
        }
@@ -159,10 +159,10 @@ project "fbx-conv"

    configuration { "macosx", "Debug" }
        libdirs {
-           (FBX_SDK_ROOT .. "/lib/gcc4/ub/debug"),
+           (FBX_SDK_ROOT .. "/lib/clang/debug"),
        }

    configuration { "macosx", "Release" }
        libdirs {
-           (FBX_SDK_ROOT .. "/lib/gcc4/ub/release"),
+           (FBX_SDK_ROOT .. "/lib/clang/release"),
        }
```

**Comment by xoppa** [comment]
Thanks! Afaik the OSX build server currently uses the 2014 version. For now best for the docs to be in line with the build server. But when we update, we'll need to apply this as well. Therefor, let's leave this open for now, so we don't forget it.

**Comment by robertlight** [comment]
I needed to do this when I build with the 2019 FBX SDK on MacOS 10.14.2 Mohave

**Comment by Tom-Ski** [comment]
Updated
