### ISSUE TITLE
G3DB and G3DJ Files Blank

### ISSUE THREAD

**Issue by DavidArayan** [libgdx/fbx-conv#87]
Greetings Xoppa,

Having an issue converting a few FBX files with the converter. The fbx files are below for testing. I'm using the latest version.

https://www.dropbox.com/s/4rwvr354tbsbi9g/building_2.fbx?dl=0

The output of the program is below.

fbx-conv-win32 -v -o G3DJ building_2.fbx
INFO:     FBX to G3Dx converter, version 0.01.0070 x32 , FBXSDK 2015.01
STATUS:   Loading source file
PROGRESS: Import FBX 100.00%
WARNING:  [Basic_Wall__WT_105__1304108__1] Node uses RrSs mode, transformation might be incorrect
VERBOSE:  [shape(Basic_Wall__WT_105__1304108__1)] polygons: 165628 (496884 indices), control points: 87210
WARNING:  Mesh contains more indices (496884) than the specified maximum (32767)
ERROR:    [shape(Basic_Wall__WT_105__1304108__1)] Skipping geometry without material
STATUS:   Converting source file
STATUS:   Closing source file
VERBOSE:  Listing model information:
VERBOSE:  ID        :
VERBOSE:  Version   : Hi=0, Lo=1
VERBOSE:  Meshes    : 0 (0 vertices, 0 parts, 0 indices)
VERBOSE:  Nodes     : 1 root, 1 total, 0 parts
VERBOSE:  Materials : 0 (0 textures)
STATUS:   Exporting to G3DJ file: building_2.g3dj
STATUS:   Closing exported file

The output G3DJ File has almost all nodes missing. This is the output file below.

{
	"version": [  0,   1], 
	"id": "", 
	"meshes": [], 
	"materials": [], 
	"nodes": [
		{
			"id": "Basic_Wall__WT_105__1304108__1", 
			"translation": [ 1005.095154, -1846.648315,  2290.166504]
		}
	], 
	"animations": []
}

Any help would be much appreciated!

**Comment by xoppa** [comment]
That fbx file contains only one node and fbx-conv is pretty clear on why it skips the geometry of that node. Also half a million indices...
