### ISSUE TITLE
It does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by Juude** [libgdx/fbx-conv#88]
./fbx-conv-lin64: error while loading shared libraries: libfbxsdk.so: cannot open shared object file: No such file or directory

have used the precompiled files,but it still not work.

**Comment by xoppa** [comment]
https://github.com/libgdx/fbx-conv#precompiled-binaries

**Comment by utgarda** [comment]
@Juude your question answered here: https://github.com/libgdx/fbx-conv/issues/80
