### ISSUE TITLE
Material not being included in g3dj file format

### ISSUE THREAD

**Issue by nimeso** [libgdx/fbx-conv#89]
I'm running the converter on windows and its not including relative paths to my texture file/material.

Here is a zip with the super simple fbx file and the texture jpg
https://drive.google.com/file/d/0B6kaPf1v_YV6TlV3UWRYSWtUeUE/view?usp=sharing
I created the fbx using Cinema 4D and if I look in the fbx file I can see the jpg reference but the converted g3dj file has no reference or material. the output says:

WARNING:  [Torus] Node uses RrSs mode, transformation might be incorrect
STATUS:   [shape(Torus)] Triangulating FbxMesh geometry
VERBOSE:  [shape(Torus)] polygons: 1296 (3888 indices), control points: 648
STATUS:   Converting source file
STATUS:   Closing source file
VERBOSE:  Listing model information:
VERBOSE:  ID        :
VERBOSE:  Version   : Hi=0, Lo=1
VERBOSE:  Meshes    : 1 (5624 vertices, 1 parts, 3888 indices)
VERBOSE:  Nodes     : 1 root, 1 total, 1 parts
VERBOSE:  Materials : 1 (0 textures)
STATUS:   Exporting to G3DJ file: torus3.g3dj
STATUS:   Closing exported file

Please can you help asap... we are happy to pay for your time :) thanks for the great work!

**Comment by xoppa** [comment]
Fbx-conv doesn't care where your textures are stored, it just uses the texture filename that the fbx file references. Please don't use the issue tracker for personal support requests.

**Comment by xoppa** [comment]
Sorry I misunderstood the issue you're reporting (thought you wanted fbx-conv to include folder names). At second read it looks like you mean the textures are not included at all. It looks like this is because you are using a layered texture. Could you please verify that it does work correctly when using a plain texture?

**Comment by nimeso** [comment]
Thanks @xoppa :)

I use Cinema4D and there is no way to create a 'normal texture' :( We are creating a product that relies heavily on being able to convert .fbx files generated from many different 3D applications so this is a bit of a issue for us ... bugger... any thoughts? 

Thanks heaps for your help :)
