### ISSUE TITLE
FBX Embedded Texture Conversion Problem

### ISSUE THREAD

**Issue by DavidArayan** [libgdx/fbx-conv#90]
Greetings Xoppa,

We have a small problem with a certain FBX exported from Cinema4D. We have the FBX model with an embedded texture. Converting the FBX into G3DJ parses the model successfully however the texture or its path is not found in the final G3DJ file.

During conversion, the embedded texture is extracted into a folder. The problem is that the texture itself or its path cannot be found in the final G3DJ File.

Dropbox link to the original FBX and the converted G3DJ file: https://www.dropbox.com/sh/f3wqxhfbqjznpg1/AAACmREBU9u_a5J-b6DyvHWNa?dl=0

fbx-conv-win32 -v -o G3DJ torus7.fbx
INFO:     FBX to G3Dx converter, version 0.01.0070 x32 , FBXSDK 2015.01
STATUS:   Loading source file
PROGRESS: Import FBX 100.00%
WARNING:  [Torus] Node uses RrSs mode, transformation might be incorrect
STATUS:   [shape(Torus)] Triangulating FbxMesh geometry
VERBOSE:  [shape(Torus)] polygons: 1296 (3888 indices), control points: 648
STATUS:   Converting source file
STATUS:   Closing source file
VERBOSE:  Listing model information:
VERBOSE:  ID        :
VERBOSE:  Version   : Hi=0, Lo=1
VERBOSE:  Meshes    : 1 (2530 vertices, 1 parts, 3888 indices)
VERBOSE:  Nodes     : 1 root, 1 total, 1 parts
VERBOSE:  Materials : 1 (0 textures)
STATUS:   Exporting to G3DJ file: torus7.g3dj
STATUS:   Closing exported file

Any help would be much appreciated!

Regards,
David Arayan

**Comment by xoppa** [comment]
Fbx-conv doesn't support embedded textures.
