### ISSUE TITLE
g3dj grouped objects with animations issues

### ISSUE THREAD

**Issue by nimeso** [libgdx/fbx-conv#91]
Seems the converter is not liking my very simple file with animations. No animations get converted :( 

MainGroup1 (is animated)
   - Group
     - Mesh
     - Mesh 
     - Mesh

MainGroup2 (is animated)
   - Group
     - Mesh
     - Mesh 
     - Mesh

the output gives me warnings: 
WARNING:  [MainGroup1] Node uses RrSs mode, transformation might be incorrect

-------------- files -------------------
fbx:
https://drive.google.com/open?id=0B6kaPf1v_YV6LTNEenJDcG05eUU
output g3dj
https://drive.google.com/open?id=0B6kaPf1v_YV6X2o1bmhiclRtc0U

------------- full output -------------
C:\fbx-conv>fbx-conv-win32.exe -f -v blobs9.fbx blobs9.g3dj
INFO:     FBX to G3Dx converter, version 0.01.0071 x32 , FBXSDK 2015.01
STATUS:   Loading source file
PROGRESS: Import FBX 1.69% Cloner
PROGRESS: Import FBX 3.39% Sphere_1
PROGRESS: Import FBX 5.08% Sphere_3
PROGRESS: Import FBX 6.78% Sphere_5
PROGRESS: Import FBX 8.47% Sphere_7
PROGRESS: Import FBX 10.17% Sphere_9
PROGRESS: Import FBX 11.86% Sphere_11
PROGRESS: Import FBX 13.56% Sphere_13
PROGRESS: Import FBX 15.25% Sphere_15
PROGRESS: Import FBX 16.95% Sphere_17
PROGRESS: Import FBX 18.64% Sphere_19
PROGRESS: Import FBX 20.34% Sphere_21
PROGRESS: Import FBX 22.03% Sphere_23
PROGRESS: Import FBX 23.73% Sphere_25
PROGRESS: Import FBX 25.42% Sphere
PROGRESS: Import FBX 27.12% Cloner_2
PROGRESS: Import FBX 28.81% Sphere_1_2
PROGRESS: Import FBX 30.51% Sphere_3_2
PROGRESS: Import FBX 32.20% Sphere_5_2
PROGRESS: Import FBX 33.90% Sphere_7_2
PROGRESS: Import FBX 35.59% Sphere_9_2
PROGRESS: Import FBX 37.29% Sphere_11_2
PROGRESS: Import FBX 38.98% Sphere_13_2
PROGRESS: Import FBX 40.68% Sphere_15_2
PROGRESS: Import FBX 42.37% Sphere_17_2
PROGRESS: Import FBX 44.07% Sphere_19_2
PROGRESS: Import FBX 45.76% Sphere_21_2
PROGRESS: Import FBX 47.46% Sphere_23_2
PROGRESS: Import FBX 49.15% Sphere_25_2
PROGRESS: Import FBX 50.85% Sphere_2_3
PROGRESS: Import FBX 52.54% C4D Animation Take
PROGRESS: Import FBX 54.24%
PROGRESS: Import FBX 55.93%
PROGRESS: Import FBX 57.63%
PROGRESS: Import FBX 59.32%
PROGRESS: Import FBX 61.02%
PROGRESS: Import FBX 62.71%
PROGRESS: Import FBX 64.41%
PROGRESS: Import FBX 66.10%
PROGRESS: Import FBX 67.80%
PROGRESS: Import FBX 69.49%
PROGRESS: Import FBX 71.19%
PROGRESS: Import FBX 72.88%
PROGRESS: Import FBX 74.58%
PROGRESS: Import FBX 76.27%
PROGRESS: Import FBX 77.97%
PROGRESS: Import FBX 79.66%
PROGRESS: Import FBX 81.36%
PROGRESS: Import FBX 83.05%
PROGRESS: Import FBX 84.75%
PROGRESS: Import FBX 86.44%
PROGRESS: Import FBX 88.14%
PROGRESS: Import FBX 89.83%
PROGRESS: Import FBX 91.53%
PROGRESS: Import FBX 93.22%
PROGRESS: Import FBX 94.92%
PROGRESS: Import FBX 96.61%
PROGRESS: Import FBX 98.31%
PROGRESS: Import FBX 100.00%

WARNING:  [Random_1] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Cloner] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_0] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_1] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_3] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_4] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_5] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_6] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_7] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_8] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_9] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_10] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_11] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_12] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_13] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_14] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_15] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_16] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_17] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_18] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_19] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_20] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_21] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_22] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_23] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_24] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_25] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_26] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Random] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Cloner_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_0_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_1_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_2_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_3_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_4_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_5_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_6_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_7_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_8_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_9_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_10_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_11_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_12_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_13_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_14_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_15_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_16_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_17_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_18_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_19_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_20_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_21_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_22_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_23_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_24_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_25_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_26_2] Node uses RrSs mode, transformation might be incorrect
WARNING:  [Sphere_2_3] Node uses RrSs mode, transformation might be incorrect
STATUS:   [shape(Sphere_0)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_1)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_3)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_4)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_5)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_6)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_7)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_8)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_9)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_10)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_11)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_12)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_13)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_14)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_15)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_16)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_17)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_18)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_19)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_20)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_21)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_22)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_23)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_24)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_25)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_26)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_0_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_1_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_2_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_3_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_4_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_5_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_6_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_7_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_8_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_9_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_10_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_11_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_12_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_13_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_14_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_15_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_16_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_17_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_18_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_19_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_20_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_21_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_22_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_23_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_24_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_25_2)] Triangulating FbxMesh geometry
STATUS:   [shape(Sphere_26_2)] Triangulating FbxMesh geometry
VERBOSE:  [shape(Sphere_0)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_1)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_3)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_4)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_5)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_6)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_7)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_8)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_9)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_10)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_11)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_12)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_13)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_14)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_15)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_16)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_17)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_18)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_19)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_20)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_21)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_22)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_23)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_24)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_25)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_26)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_0_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_1_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_2_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_3_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_4_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_5_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_6_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_7_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_8_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_9_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_10_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_11_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_12_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_13_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_14_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_15_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_16_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_17_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_18_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_19_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_20_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_21_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_22_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_23_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_24_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_25_2)] polygons: 120 (360 indices), control points: 62
VERBOSE:  [shape(Sphere_26_2)] polygons: 120 (360 indices), control points: 62
STATUS:   Converting source file
STATUS:   Closing source file
VERBOSE:  Listing model information:
VERBOSE:  ID        :
VERBOSE:  Version   : Hi=0, Lo=1
VERBOSE:  Meshes    : 1 (178 vertices, 54 parts, 19440 indices)
VERBOSE:  Nodes     : 2 root, 60 total, 54 parts
VERBOSE:  Materials : 1 (0 textures)
STATUS:   Exporting to G3DJ file: blobs9.g3dj
STATUS:   Closing exported file

**Comment by xoppa** [comment]
This is an issue tracker. Please use the forum or irc if you need help. https://github.com/libgdx/libgdx/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Comment by nimeso** [comment]
@xoppa I can't register on the forum. It's asking for the current libgdx version before I can register ... I've tried 1.6.1 1.6.0 etc etc etc. Now it says I've tried too many times and I have to wait :( gutted
