### ISSUE TITLE
Compilation failes on VS2015

### ISSUE THREAD

**Issue by noosxe** [libgdx/fbx-conv#95]
Hi!
I'm trying to build fbx-conv's master branch source using VS2015 and get this error:

error C2338: va_start argument must not have reference type and must not be parenthesized (compiling source file ....\src\main.cpp)

any ideas how to fix this ?

**Comment by Tuee22** [comment]
I had a similar issue with some code I had written, and which successfully compiled and ran, using VS2013 express. As soon as I upgraded to 2015 (professional in my case) I got the error you described.

I was able to resolve the problem via:
#define _CRT_NO_VA_START_VALIDATION

(I just added _CRT_NO_VA_START_VALIDATION to the preprocessor definitions under C/C++ -> preprocessor under project properties.)

**Comment by Tom-Ski** [comment]
Thanks for the workaround @Tuee22
